### ISSUE TITLE
Update "About" section of Git

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/shpc-registry-cache#11]

**Comment by marcodelapierre** [comment]
Something like "A cache of container executables (currently featuring the BioContainers)"

**Comment by vsoch** [comment]
![image](https://user-images.githubusercontent.com/814322/202976180-ead865f4-dc8f-4e33-a625-3109ac3c934c.png)

**Comment by vsoch** [comment]
The filing box emoji seemed appropriate :laughing:

**Comment by marcodelapierre** [comment]
Beautiful!! 😆
