### ISSUE TITLE
Does the README for this repo need more info? 

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/shpc-registry-cache#12]
@vsoch this is my last picky one for today :-)

E.g. can you compare with the README for the shpc-registry?
https://github.com/singularityhub/shpc-registry

**Comment by vsoch** [comment]
yeah agree - let me work on this now. :+1:

**Comment by vsoch** [comment]
See https://github.com/singularityhub/shpc-registry-cache/pull/13 !
