### ISSUE TITLE
Add versioned release

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/shpc-registry-cache#9]
Hi @vsoch  I think we should tag releases in this repo, as this is one of the main software products related to the automated cache manuscript!

**Comment by vsoch** [comment]
Sure - how about a monthly release like with the registry?

**Comment by marcodelapierre** [comment]
Sounds great!

**Comment by vsoch** [comment]
Done! https://github.com/singularityhub/shpc-registry-cache/commit/a7db03628bcd5fb0ad3ee9e74dc3fd99d21f69d8

**Comment by marcodelapierre** [comment]
Can you manually trigger the November release now? 
So that we can point to a version within the manuscript :-)

**Comment by vsoch** [comment]
Sure! I'll just date it for today, since the "official" November release won't be until December 2nd and will include the rest of this month.

**Comment by marcodelapierre** [comment]
Perfect!

**Comment by vsoch** [comment]
I just tagged it to coincide with October so the format is the same, but in the content noted it was done today. https://github.com/singularityhub/shpc-registry-cache/releases/tag/2022-10
